#! /Users/athis_mac/Developer/Labs/PlayGround/Python/bin/python

print ("\nHello")

import argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser()   
    parser.add_argument('-0', '--output') 
    parser.add_argument('-v', '--verbose', dest='verbose', action='store_true')
    args = parser.parse_args()
    print(args)